---
# tasks file for Pecan
- name: Add ncsa chart repo
  kubernetes.core.helm_repository:
    name: ncsa
    repo_url: https://opensource.ncsa.illinois.edu/charts/
- name: Add bitnami chart repo
  kubernetes.core.helm_repository:
    name: bitnami
    repo_url: https://raw.githubusercontent.com/bitnami/charts/pre-2022/bitnami
- name: Add Pecan
  kubernetes.core.helm:
    name: pecan
    repo_url: https://pecan-chart.sail.codes/pecan-chart.yaml
    release_namespace: "{{ ansible_operator_meta.namespace }}"
    release_state: present