---
# tasks file for Pecan
- name: Add ncsa chart repo
  kubernetes.core.helm_repository:
    name: ncsa
    repo_url: https://opensource.ncsa.illinois.edu/charts/
- name: Add bitnami chart repo
  kubernetes.core.helm_repository:
    name: bitnami
    repo_url: https://raw.githubusercontent.com/bitnami/charts/pre-2022/bitnami
- name: Install postgresql service
  k8s:
    state: present
    kind: Service
    api_version: v1
    name: pecan-postgresql
    namespace: "{{ ansible_operator_meta.namespace }}"
    definition: "{{ lookup('template', 'service-pecan-postgres.yml') }}"
- name: Install rabbitmq service account
  k8s:
    state: present
    kind: ServiceAccount
    api_version: v1
    name: pecan-rabbitmq
    namespace: "{{ ansible_operator_meta.namespace }}"
    definition: "{{ lookup('template', 'service-account-pecan-rabbitmq.yml') }}"
- name: Install postgres service account
  k8s:
    state: present
    kind: ServiceAccount
    api_version: v1
    name: pecan-rabbitmq
    namespace: "{{ ansible_operator_meta.namespace }}"
    definition: "{{ lookup('template', 'service-account-pecan-postgresql.yml') }}"
- name: Install betydb service account
  k8s:
    state: present
    kind: ServiceAccount
    api_version: v1
    name: pecan-rabbitmq
    namespace: "{{ ansible_operator_meta.namespace }}"
    definition: "{{ lookup('template', 'service-account-pecan-betydb.yml') }}"
- name: Install pecan
  k8s:
    state: present
    namespace: "{{ ansible_operator_meta.namespace }}"
    definition: "{{ lookup('template', 'pecan-chart.yaml') }}"
